
scripts:
    start: react-app-rewired start
    build: react-app-rewired build
    test: react-app-rewired test
    eject: react-scripts eject
dependencies:
    normalize.css: ^8.0.1
devDependencies:
    babel-plugin-module-resolver: ^5.0.0
    customize-cra: ^1.0.0
    react-app-rewired: ^2.2.1
    sass: ^1.62.1